//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beeline.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int IdDogovor { get; set; }
        public int IdTarif { get; set; }
        public int IdClient { get; set; }
        public int IdSotr { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sotr Sotr { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tarif Tarif { get; set; }
    }
}
