//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beeline.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int IdPhone { get; set; }
        public string Number { get; set; }
        public int IdStatusPhone { get; set; }
    
        public virtual StatusPhone StatusPhone { get; set; }
    }
}
